# Generated by Django 3.2.7 on 2021-10-19 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0003_alter_courseuserrelation_is_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='sol_description',
        ),
        migrations.RemoveField(
            model_name='assignments',
            name='solutionfile',
        ),
        migrations.RemoveField(
            model_name='assignments',
            name='submission_time',
        ),
        migrations.AlterField(
            model_name='assignments',
            name='problemfile',
            field=models.FileField(blank=True, null=True, upload_to='assignments/problem'),
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solutionfile', models.FileField(blank=True, null=True, upload_to='assignments/solutions')),
                ('sol_description', models.TextField(blank=True)),
                ('submission_time', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.assignments')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
