# Generated by Django 3.2.7 on 2021-10-19 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20211019_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solutions',
            old_name='sol_description',
            new_name='feedback',
        ),
    ]
