# Generated by Django 3.2.7 on 2021-10-19 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_rename_sol_description_solutions_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutions',
            name='feedback',
        ),
        migrations.CreateModel(
            name='SolutionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True)),
                ('solution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userprofile.solutions')),
            ],
        ),
    ]
