# Generated by Django 3.2.7 on 2021-11-23 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_csvfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='course_weightage',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignments',
            name='max_marks',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
