# Generated by Django 3.2.7 on 2021-11-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_csvfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseuserrelation',
            name='is_TA',
            field=models.BooleanField(default=False),
        ),
    ]
