# Generated by Django 3.2.7 on 2021-11-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_auto_20211123_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionfeedback',
            name='marks_obtained',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
