# Generated by Django 3.2.7 on 2021-11-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_courseuserrelation_is_ta'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='regcode_TA',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='regcode_student',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
