# Generated by Django 3.2.7 on 2021-11-24 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_lecturecompleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturecompleted',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.lecture'),
        ),
    ]
