# Generated by Django 3.2.7 on 2021-11-26 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_auto_20211123_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='forums_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ForumQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.course')),
            ],
        ),
        migrations.CreateModel(
            name='ForumAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.forumquestions')),
            ],
        ),
    ]
