# Generated by Django 3.2.7 on 2021-11-25 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_alter_lecturecompleted_lecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='course_weightage',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
