# Generated by Django 3.2.7 on 2021-11-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0015_alter_assignments_course_weightage'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='assignment_name',
            field=models.CharField(default='assignment unnamed', max_length=100),
            preserve_default=False,
        ),
    ]
