# Generated by Django 3.2.7 on 2021-11-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0016_assignments_assignment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionfeedback',
            name='marks_obtained',
            field=models.FloatField(default=0.0),
        ),
    ]
